@echo off
setlocal
set "CLAUDE_CONFIG_DIR="
if defined REMEMBER_REAL_HOME set "HOME=%REMEMBER_REAL_HOME%"
if defined REMEMBER_REAL_USERPROFILE set "USERPROFILE=%REMEMBER_REAL_USERPROFILE%"
if not defined REMEMBER_REAL_CLAUDE_BIN set "REMEMBER_REAL_CLAUDE_BIN=%USERPROFILE%\.local\bin\claude.exe"
"%REMEMBER_REAL_CLAUDE_BIN%" %*
exit /b %ERRORLEVEL%
